### ISSUE TITLE
Thumbnails path doesn't match icon path in prefab.

### ISSUE THREAD

**Issue by rogerwong2** [CitiesSkylinesModding/CS2-AssetPacksManager#13] opened 2024-11-02 06:35 UTC
## What is the issue
Thumbnails path doesn't match icon path in prefab.
Here is the path defined in prefab as an example:  "m_Icon": "coui://customassets/MiniParksPack_AssetPack/Grill zone/Grill zone.png",
And here is the file on my computer:"AppData\LocalLow\Colossal Order\Cities Skylines II\ModsData\AssetPacksManager\thumbnails\Grill zone.png"
Looks like "MiniParksPack_AssetPack/Grill zone" is missing.
Not sure if this is a regression please take a look.

## Have you used the `Delete Mods Cache`-Option in Asset Packs Manager? If not, why not?
No

## Have you deleted the `C:/Users/%username%/AppData/LocalLow/Colossal Order/Cities Skylines II/Mods` folder? If not, why not?
No

## Have you deleted the `C:/Users/%username%/AppData/LocalLow/Colossal Order/Cities Skylines II/CustomAssets` folder? If not, why not?
No

**Comment by Mimonsi** [comment] 2024-11-02 10:22
Thanks for the report, it is indeed a regression error, because I didn't delete all my local data in Testing. Working on a fix

**Comment by Mimonsi** [comment] 2024-11-02 10:42
Fixed with Version 1.5.1

**Closed as completed** 2024-11-02 10:42 UTC
Labels: assistance needed
